version: '3.1'

services:
  mariaDb:
    image: mariadb:noble
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: _AdminSeg_2024
    ports:
      - 27030:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariaDb
